### ISSUE TITLE
[Archipelago] Slot settings are not being loaded/set correctly from .yaml file; settings desynced from toggle states

### ISSUE THREAD

**Issue by ScorelessPine** [mryamiouji/pm64r-tracker#4]
When connecting to an Archipelago slot and providing a .yaml file, the settings don't appear to be set correctly from the yaml. For one example, when loading into a slot with "Partners Always Usable" set to false in the yaml, the website shows the toggle for that option as Off under Logic Settings, but all locations are actually behaving as if the option was set to On, as seen in the screenshot below, the player does not have Sushi, but Main Gate's "Item bottom left of the map" is shown as in logic despite claiming Partners Always Usable is Off.

![Image](https://github.com/user-attachments/assets/500be030-527c-4717-bd3d-b749f38f24bf)

When the option is manually toggled On and then back Off, all the checks correctly show the logic for Partners Always Usable turned Off again, as seen in the screenshot here:

![Image](https://github.com/user-attachments/assets/4383261d-ca10-4390-9d83-61e03ca94b52)

This issue affects most settings that I could find, and causes the user to need to re-toggle every setting or re-set every setting from their yaml manually in order to have the correct logic, which completely negates the purpose of importing a yaml to import the settings.

**Comment by mryamiouji** [comment]
I should be fixed. It's now loading from the configs directly on login.

Feel free to post another issue if it's happening again!

**Comment by ScorelessPine** [comment]
EDIT: My bad, I must have not yet cleared my cache as for some reason the old version of the page was loading. I loaded the most recent version and the issues do seem to be resolved, sorry!

~~Hi, I'm still seeing this issue with the latest version. When I load my yaml and connect to an Archipelago room, many of the settings are still wrong, such as "Shuffle Dungeon Entrances". This option isn't even an implemented for Archipelago seeds yet, but the tracker is acting as if it is on, while showing the option as if it is off.~~


~~I'm not sure what is different between your testing and my experience, but this issue is very much not resolved yet, as this still affects a majority of Randomizer Settings and Logic Settings.~~

~~Also, now the "Equipments" and all of my obtained Partners are not properly tracking either. In my game, I should have Super Boots, Ultra Hammer, Goombario, Parakarry, Bow, Watt, and Sushie, but the tracker says I have none of those.~~

**Comment by ScorelessPine** [comment]
I also believe there are other issues, as many of the tracked locations seem to just be wrong, compared to the locations I actually have not yet obtained

![Image](https://github.com/user-attachments/assets/6003b0f5-ec22-43ab-9d6b-928304632f40)

![Image](https://github.com/user-attachments/assets/8ee2096d-0423-4133-bbea-e8d957afea77)
